---
- name: Ensure docker
  hosts: "all"
  gather_facts: false
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - ubuntu
      
- name: Install awscli
  hosts: "all"
  gather_facts: false
  become: true
  tasks:
    - name: Install APT
      apt:
        name: awscli
        state: present
